---
- name: Set UFW default incoming policy to deny
  community.general.ufw:
    default: deny
    direction: incoming

- name: Set UFW default outgoing policy to allow
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow SSH from anywhere
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP on workers (nginx)
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp
  when: "'workers' in group_names"

- name: Allow MariaDB only from worker IP
  community.general.ufw:
    rule: allow
    port: "{{ db_port }}"
    proto: tcp
    src: "{{ hostvars['worker01']['ansible_host'] }}"
  when: "'db' in group_names"

- name: Enable UFW
  community.general.ufw:
    state: enabled
